<?php

namespace AppBundle\Repository;

/**
 * ActivityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
