<?php

namespace AppBundle\Repository;

/**
 * CivilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CivilityRepository extends \Doctrine\ORM\EntityRepository
{
}
