<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'desc']);
    }

    public function getLastInvoice(\DateTime $date)
    {
        return $this->createQueryBuilder('i')
            ->where('i.date >= :min')
            ->setParameter('min', $date->format('Y-01-01'))
            ->andWhere('i.date <= :max')
            ->setParameter('max', $date->format('Y-12-31'))
            ->addOrderBy('i.numerous', 'DESC')
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
    }
}
