<?php

namespace AppBundle\Repository;

/**
 * InvoiceActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
