<?php

namespace AppBundle\Repository;

/**
 * QuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'desc']);
    }

    public function getLastQuotation(\DateTime $date)
    {
        return $this->createQueryBuilder('q')
            ->where('q.date >= :min')
            ->setParameter('min', $date->format('Y-01-01'))
            ->andWhere('q.date <= :max')
            ->setParameter('max', $date->format('Y-12-31'))
            ->addOrderBy('q.numerous', 'DESC')
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
    }
}
